### ISSUE TITLE
请问下，client能提交下整个项目的资源文件吗

### ISSUE THREAD

**Issue by awen233333** [WiwilZ/510KPokerGame#1]

**Comment by WiwilZ** [comment]
好的，我整理下。不过我新项目用微信小程序写了。

**Comment by awen233333** [comment]
> 好的，我整理下。不过我新项目用微信小程序写了。

大佬，微信小程序项目有缺文件吗？我用微信开发者工具打开编译不了，说缺少app.json，我没学过小程序开发，想部署上去和朋友玩

**Comment by WiwilZ** [comment]
> 

你得用最新版的微信开发者工具的小游戏模式打开
